export const VERSES_SCREEN_TITLE = 'VERSES';
export const SET_BUTTON_TITLE = 'SET';
export const FOLDER_BUTTON_TITLE = 'FOLDERS';
export const CREATE_SET_BUTTON_TITLE = 'CREATE SET';
export const CREATE_FOLDER_BUTTON_TITLE = 'CREATE FOLDER';