export const VERSES_SCREEN_TITLE = 'VERSES';
export const SET_BUTTON_TITLE = 'SET';
export const FOLDER_BUTTON_TITLE = 'FOLDERS';
export const CREATE_SET_BUTTON_TITLE = 'CREATE SET';
export const CREATE_FOLDER_BUTTON_TITLE = 'CREATE FOLDER';
export const DONE_BUTTON_TITLE = 'DONE';
export const CREATE_SET_HEADER_TITLE = 'CREATE SET';
export const CREATE_FOLDER_HEADER_TITLE = 'CREATE FOLDER';